Algoritmo "Número Proibido"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

n1, n2: inteiro

Inicio

Escreva ("Escreva um número: ")
Leia (n1)

Escreva ("Pessa para alguém escreverer um número: ")
Leia (n2)

Se (não (n1 = n2)) então
   Escreva ("Ufa! Se livrou dessa.")
   Senão
        Escreva ("Que pena, vocês perderam!")
Fimse

Fimalgoritmo