Algoritmo "A+B=C"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

a, b, c: inteiro

Inicio

Escreva ("Escreva os valores A, B e C, respecticamente: ")
Leia (a, b, c)

Escreva (a + b = c)

Fimalgoritmo

Crie um programa que leia três números inteiros e verifique se a soma dos
dois primeiros é igual ao terceiro. Exiba "VERDADEIRO" se a soma for igual,
e "FALSO" caso contrário.