Algoritmo "A é duas vezes maior que B?"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

n1, n2: inteiro

Inicio

Escreva ("Qual o valor do seu A? ")
Leia (n1)

Escreva ("Qual o valor do sei B? ")
Leia (n2)

Escreva (n1 = (2*n2))

Fimalgoritmo

Escreva um algoritmo que leia dois números inteiros e verifique se o primeiro
é maior que o dobro do segundo. Exiba "VERDADEIRO" se for maior, e "FALSO"
caso contrário.