Algoritmo "tabuada 1 a 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/07/2025
Var

n, i: inteiro

Inicio

escreval ("Qual a tabuada desejada? ")
leia (n)
escreval ("")
escreval ("=======================")
escreval ("")

para i <- 1 ate 10 faca
escreval (n, " x ", i, " = ", i*n)
fimpara

Fimalgoritmo