Algoritmo "soma de 1 a 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/07/2025
Var

   i, soma: inteiro

Inicio

   para i <- 0 ate 10 faca
   soma <- soma + i
   fimpara

   escreval ("A soma dos números de 1 a 10 é: ", soma)

Fimalgoritmo