Algoritmo "ímpares de 9 a 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/07/2025
Var

i: inteiro

Inicio

   para i <- 9 ate 1 passo -1 faca

      se (i % 2 = 1) entao
         escreval (i)
      fimse

   fimpara

Fimalgoritmo

Exiba os números ímpares de 9 a 1 em ordem decrescente.